FROM savoirfairelinux/ring-fedora32:24

RUN dnf clean all
RUN dnf install -y yum-utils rpmdevtools

RUN dnf clean all
RUN dnf upgrade -y && \
    dnf install -y \
        rpm-build \
        tar \
        make \
        autoconf \
        automake \
        cmake \
        speexdsp-devel \
        pulseaudio-libs-devel \
        libsamplerate-devel \
        libtool \
        dbus-devel \
        expat-devel \
        pcre-devel \
        yaml-cpp-devel \
        boost-devel \
        dbus-c++-devel \
        dbus-devel \
        libsndfile-devel \
        libXext-devel \
        libXfixes-devel \
        yasm \
        speex-devel \
        gsm-devel \
        chrpath \
        check \
        astyle \
        uuid-c++-devel \
        libupnp-devel \
        gettext-devel \
        gcc-c++ \
        which \
        alsa-lib-devel \
        systemd-devel \
        libuuid-devel \
        uuid-devel \
        gnutls-devel \
        nettle-devel \
        opus-devel \
        patch \
        jsoncpp-devel \
        libnatpmp-devel \
        libva-devel

ADD scripts/build-package-fedora.sh /opt/build-package-fedora.sh

CMD /opt/build-package-fedora.sh
