FROM ubuntu:21.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y -o Acquire::Retries=10 \
        devscripts \
        equivs \
        wget

# add deb-src entries (needed for next step)
RUN sed -n '/^deb\s/s//deb-src /p' /etc/apt/sources.list > /etc/apt/sources.list.d/deb-src.list
RUN apt-get clean && apt-get update

COPY packaging/rules/debian-qt/* /tmp/builddeps/debian/
RUN cd /tmp/builddeps && \
    apt-get update; \
    mk-build-deps \
        --remove --install \
        --tool "apt-get -y --no-install-recommends -o Acquire::Retries=10" \
        "debian/control"; \
    cd / && rm -rf /tmp/builddeps

ADD scripts/build-package-debian.sh /opt/build-package-debian.sh
RUN /opt/build-package-debian.sh qt

COPY packaging/rules/debian/* /tmp/builddeps/debian/
RUN cd /tmp/builddeps && \
    apt-get update; \
    mk-build-deps \
        --remove --install \
        --tool "apt-get -y --no-install-recommends -o Acquire::Retries=10" \
        "debian/control"; \
    cd / && rm -rf /tmp/builddeps

CMD /opt/build-package-debian.sh
