FROM debian:buster

# Non root user with sudo
RUN apt-get update && apt-get install --no-install-recommends -y sudo
RUN useradd -ms /bin/bash -G sudo user
RUN sed -i 's/^%sudo.*/%sudo ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers

# Required to add jami repos to debian
RUN apt-get install --no-install-recommends -y \
	gnupg \
	dirmngr \
	ca-certificates

# Jami dependencies in the advance (made jami installation faster)
RUN apt install --no-install-recommends -y \
	libappindicator3-1  \
        libatk1.0-0  \
        libc6  \
        libcairo-gobject2  \
        libcairo2  \
        libcanberra-gtk3-0  \
        libcanberra0  \
        libclutter-1.0-0  \
        libclutter-gtk-1.0-0  \
        libcogl-pango20  \
        libcogl-path20  \
        libcogl20  \
        libdbusmenu-glib4  \
        libdrm2  \
        libegl1 \
        libgbm1  \
        libgcc1  \
        libgdk-pixbuf2.0-0  \
        libglib2.0-0  \
        libgtk-3-0  \
        libjavascriptcoregtk-4.0-18 \
        libjson-glib-1.0-0  \
        libnm0  \
        libnotify4  \
        libpango-1.0-0  \
        libpangocairo-1.0-0  \
        libqrencode4  \
        libqt5core5a  \
        libqt5dbus5  \
        libqt5gui5  \
        libqt5sql5  \
        libsoup2.4-1  \
        libstdc++6  \
        libwayland-client0  \
        libwayland-cursor0  \
        libwayland-egl1  \
        libwayland-server0  \
        libwebkit2gtk-4.0-37  \
        libx11-6 \
        libxcomposite1  \
        libxdamage1  \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxkbcommon0  \
        libxrandr2 \
        libqt5sql5-sqlite

# Jami daemon dependencies in the advance (made jami installation faster)
RUN apt install --no-install-recommends -y \
	libargon2-1  \
        libasound2  \
        libatomic1  \
        libavcodec58  \
        libavdevice58  \
        libavfilter7  \
        libavformat58  \
        libavutil56  \
        libc6  \
        libdbus-1-3  \
        libgcc1  \
        libhogweed4  \
        libixml10  \
        libjsoncpp1  \
        libnatpmp1  \
        libnettle6  \
        libopus0  \
        libpulse0  \
        libspeexdsp1  \
        libssl1.1  \
        libstdc++6  \
        libswresample3  \
        libswscale5  \
        libudev1  \
        libupnp13  \
        libuuid1  \
        libyaml-cpp0.6  \
        zlib1g


USER user
WORKDIR /home/user
