FROM ubuntu:18.04
# Non root user with sudo
RUN apt-get update && apt-get install --no-install-recommends -y sudo
RUN useradd -ms /bin/bash -G sudo user
RUN sed -i 's/^%sudo.*/%sudo ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
# Required to add jami repos to debian

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get install --no-install-recommends -y \
	gnupg \
	dirmngr \
	ca-certificates \
	apt-transport-https
RUN apt-get clean
RUN apt-get update && \
    apt-get install -y vim devscripts equivs \ 
        binutils \
        xz-utils \
        wget 
# Speed up mk-build-deps
RUN apt-get clean
RUN apt-get update && \
    apt-get install -y -o Acquire::Retries=10 \
	libqt5sql5-sqlite \
	gnupg \
	libargon2-0  \
	libasound2  \
	libavcodec57  \
	libavdevice57  \
	libavfilter6  \
	libavformat57  \
	libavutil55  \
	libayatana-appindicator3-1  \
	libc6  \
	libcairo2  \
	libcanberra-gtk3-0  \
	libcanberra0  \
	libclutter-1.0-0  \
	libclutter-gtk-1.0-0  \
	libdbus-1-3  \
	libgcc1  \
	libgdk-pixbuf2.0-0  \
	libglib2.0-0  \
	libgtk-3-0  \
	libjsoncpp1  \
	libnatpmp1  \
	libnm0  \
	libnotify4  \
	libpango-1.0-0  \
	libpulse0  \
	libqrencode3  \
	libqt5core5a  \
	libqt5dbus5  \
	libqt5gui5  \
	libqt5sql5  \
	libssl1.1  \
	libstdc++6  \
	libswresample2  \
	libswscale4  \
	libudev1  \
	libuuid1  \
	libwebkit2gtk-4.0-37  \
	libx11-6 \
	zlib1g  \
	dconf-gsettings-backend \
	gsettings-backend 
USER user
WORKDIR /home/user
