FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y vim devscripts equivs

# Speed up mk-build-deps
RUN apt-get update && \
    apt-get install -y autoconf automake cmake libtool libdbus-1-dev \
                       libdbus-c++-dev libupnp-dev libgnutls28-dev \
                       libebook1.2-dev libclutter-gtk-1.0-dev \
                       libclutter-1.0-dev libglib2.0-dev libgtk-3-dev \
                       libnotify-dev qtbase5-dev qttools5-dev \
                       qttools5-dev-tools yasm unbound-anchor git-core \
                       autotools-dev gnome-icon-theme-symbolic gettext \
                       libpulse-dev libsamplerate0-dev libasound2-dev \
                       libexpat1-dev libpcre3-dev libyaml-cpp-dev \
                       libboost-dev libsndfile1-dev libsrtp-dev \
                       libxext-dev libxfixes-dev autopoint libspeex-dev \
                       libspeexdsp-dev chrpath uuid-dev libavcodec-dev \
                       libavutil-dev libavformat-dev libswscale-dev \
                       libavdevice-dev libopus-dev libudev-dev libticonv-dev \
                       libgsm1-dev libjsoncpp-dev libqrencode-dev libappindicator3-dev \
                       libnatpmp-dev libnm-dev

ADD scripts/build-package-debian.sh /opt/build-package-debian.sh

CMD /opt/build-package-debian.sh
