#FROM docker.io/roboxes/rhel8
FROM rhel_8_subscribed

RUN dnf clean all
RUN dnf install -y dnf-command\(builddep\) rpmdevtools

RUN dnf clean all
RUN dnf upgrade -y && \
#    dnf install -y mesa-libgbm-devel mesa-dri-drivers && \
    dnf install -y mesa-dri-drivers && \
#    dnf install -y libinput-devel && \
    dnf install -y \
        git \
        rpm-build \
        tar \
        make \
        autoconf \
        automake \
        cmake \
        pulseaudio-libs-devel \
        libcanberra-devel \
        libcurl-devel \
        libtool \
        dbus-devel \
        expat-devel \
        pcre-devel \
        boost-devel \
        dbus-devel \
        libXext-devel \
        libXfixes-devel \
        chrpath \
        check \
        gettext-devel \
        gcc-c++ \
        which \
        alsa-lib-devel \
        systemd-devel \
        libuuid-devel \
        gnutls-devel \
        nettle-devel \
        patch \
        webkitgtk4-devel \
        libva-devel \
        openssl-devel \
	qt5-devel \ 
	clutter \
	clutter-devel \
	clutter-gtk-devel \
	qrencode-devel \
        yasm \
        opus \
        opus-devel \
        libvdpau-devel \
        libvdpau \
        speexdsp \
        speexdsp-devel \
	cppunit-devel \
	cppunit \
	dbus-c++
 




ADD scripts/build-package-rhel.sh  /opt/build-package-rhel.sh

CMD /opt/build-package-rhel.sh
