FROM debian:buster

# FIXME: dirty qemu-static hack required because our Jenkins node runs Docker 17
# Remove next line as soon as we get Docker 18 +
COPY qemu-static/qemu-arm-static /usr/bin/qemu-arm-static

ENV DEBIAN_FRONTEND noninteractive

# Add armhf dpkg architecture
RUN dpkg --add-architecture armhf

RUN apt-get clean
RUN apt-get -o Acquire::Check-Date=false -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y vim devscripts

# Install cross-compiling tools
RUN apt install -y \
    -o Acquire::Retires=10 -o Acquire::Check-Date=false -o Acquire::Check-Valid-Until=false \
    gcc-8-arm-linux-gnueabihf-base \
    gcc-arm-linux-gnueabihf \
    binutils-arm-linux-gnueabihf \
    g++-arm-linux-gnueabihf \
    cpp-arm-linux-gnueabihf \
    binutils-arm-linux-gnueabihf-dbg \
    crossbuild-essential-armhf \
    build-essential

# Speed up mk-build-deps
RUN apt-get clean
RUN apt-get -o Acquire::Check-Date=false -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y -o Acquire::Retires=10 \
        git \
        autoconf \
        automake \
        autopoint \
        cmake \
        libtool \
        nasm \
        libdbus-1-dev \
        libdbus-c++-dev \
        libargon2-0-dev \
        libcanberra-gtk3-dev:armhf \
        libclutter-gtk-1.0-dev:armhf \
        libclutter-1.0-dev:armhf \
        libglib2.0-dev \
        libgtk-3-dev \
        libnotify-dev \
        qtbase5-dev \
        qttools5-dev \
        qttools5-dev-tools \
        yasm \
        autotools-dev \
        gettext \
        libpulse-dev \
        libasound2-dev \
        libexpat1-dev \
        libpcre3-dev \
        libyaml-cpp-dev \
        libboost-dev \
        libxext-dev \
        libxfixes-dev \
        libspeex-dev \
        libspeexdsp-dev \
        uuid-dev \
        libavcodec-dev \
        libavutil-dev \
        libavformat-dev \
        libswscale-dev \
        libavdevice-dev \
        libopus-dev \
        libudev-dev \
        libgsm1-dev \
        libjsoncpp-dev \
        libmsgpack-dev \
        libnatpmp-dev \
        libappindicator3-dev \
        libqrencode-dev \
        libnm-dev \
        libwebkit2gtk-4.0-dev \
        libcrypto++-dev \
        libva-dev \
        libvdpau-dev \
        libssl-dev

# Add stretch apt repositories to be able to install libssl1.0.0
# packages.
RUN echo 'deb http://deb.debian.org/debian/ stretch main contrib non-free' >> /etc/apt/sources.list
RUN echo 'deb-src http://deb.debian.org/debian stretch main contrib non-free' >> /etc/apt/sources.list

RUN apt update \
    -o Acquire::Check-Date=false -o Acquire::Check-Valid-Until=false && \
    apt install -y \
    -o Acquire::Retires=10 -o Acquire::Check-Date=false -o Acquire::Check-Valid-Until=false \
    libssl1.0-dev:armhf

ADD scripts/build-package-debian.sh /opt/build-package-debian.sh

CMD /opt/build-package-debian.sh
