FROM opensuse/leap:15.2

RUN zypper --non-interactive install -y \
        dnf \
        dnf-command\(builddep\) \
        rpmdevtools \
        Mesa-dri-devel Mesa-dri \
        git \
        gcc9 \
        gcc9-c++ \
        rpm-build \
        tar \
        make \
        autoconf \
        automake \
        nasm \
        speexdsp-devel \
        libpulse-devel \
        libcanberra-devel \
        libcurl-devel \
        libtool \
        pcre-devel \
        yaml-cpp-devel \
        libdbus-c++-devel \
        libXext-devel \
        libXfixes-devel \
        yasm \
        speex-devel \
        libgsm-devel \
        chrpath \
        check \
        astyle \
        gettext-devel \
        which \
        alsa-lib-devel \
        systemd-devel \
        libuuid-devel \
        uuid-devel \
        gnutls-devel \
        libopus-devel \
        patch \
        jsoncpp-devel \
        webkit2gtk3-devel \
        libcryptopp-devel \
        libva-devel \
        libvdpau-devel \
        msgpack-devel \
        clutter-devel \
        openssl-devel \
        clutter-gtk-devel \
        libnma-devel \
        libcryptopp-devel \
        libdbus-c++-devel \
        libexpat-devel \
        gnome-icon-theme-symbolic \
        libgsm-devel \
        gtk3-devel \
        libappindicator-devel \
        sqlite-devel \
        ffmpeg-4-libavutil-devel \
        gtk3-devel\
        qrencode-devel \
        python3-python-dateutil \
        libsndfile-devel \
        libdrm \
        gperf \
        bison \
        flex \
        nodejs12 \
        mozilla-nss-devel \
        python-xml \
        libxcb* \
        libxkb* \
        libX11-devel \
        libXrender-devel \
        libfreetype6 \
        xcb-util-image-devel \
        xcb-util-keysyms-devel \
        xcb-util-renderutil-devel \
        xcb-util-wm-devel \
        xorg-x11-devel \
        xz \
        xkeyboard-config \
        libnotify \
        argon2-devel \
        wget

RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 50
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 50

RUN wget https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-Linux-x86_64.sh \
      -q -O /tmp/cmake-install.sh \
      && chmod u+x /tmp/cmake-install.sh \
      && mkdir /usr/bin/cmake || true \
      && /tmp/cmake-install.sh --skip-license --prefix=/usr/local/ \
      && rm /tmp/cmake-install.sh

ADD scripts/build-package-rpm.sh  /opt/build-package-rpm.sh

CMD ["/opt/build-package-rpm.sh"]
