FROM debian:buster

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y -o Acquire::Retries=10 \
        devscripts \
        nodejs \
        vim \
        wget

# add/enable src repos (needed for next step)
RUN sed -n '/^deb\s/s//deb-src /p' /etc/apt/sources.list > /etc/apt/sources.list.d/deb-src.list

RUN pwd && ls -la /opt
RUN apt-get clean && apt-get update
RUN if [ -z "${OVERRIDE_PACKAGING_DIR}" ]; then \
        cd "packaging/rules" && mk-build-deps \
            --remove --install \
            --tool "apt-get -y --no-install-recommends -o Acquire::Retries=10" \
            "debian-qt/control"; \
    else \
        cd "${OVERRIDE_PACKAGING_DIR}" && mk-build-deps \
            --remove --install \
            --tool "apt-get -y --no-install-recommends -o Acquire::Retries=10" \
            "control"; \
    fi

ADD scripts/build-package-debian-qt.sh /opt/build-package-debian-qt.sh

CMD /opt/build-package-debian-qt.sh
