FROM gentoo/stage3-amd64:latest

RUN emerge-webrsync

ADD scripts/gentoo/portage/ /etc/portage/

ADD scripts/gentoo/locale.gen /etc/

RUN mkdir /opt/output

# profile with gnome and systemd configuration
RUN eselect profile set 5 && \
	emerge -uDN world

RUN eselect news read

RUN emerge layman && sed -i.bak '/^check_official/d' /etc/layman/layman.cfg && echo "check_official : No" >> /etc/layman/layman.cfg

ADD scripts/build-package-gentoo.sh /opt/build-package-gentoo.sh

CMD /bin/bash /opt/build-package-gentoo.sh

