FROM ubuntu:20.10

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y -o Acquire::Retries=10 \
        devscripts \
        equivs \
        wget

# add deb-src entries (needed for next step)
RUN sed -n '/^deb\s/s//deb-src /p' /etc/apt/sources.list > /etc/apt/sources.list.d/deb-src.list
RUN apt-get clean && apt-get update

COPY packaging/rules/debian-qt/* /tmp/builddeps/debian/
RUN scripts/prebuild-package-debian.sh qt-deps

COPY packaging/rules/debian/* /tmp/builddeps/debian/
RUN scripts/prebuild-package-debian.sh jami-deps

ADD scripts/build-package-debian.sh /opt/build-package-debian.sh
CMD /opt/build-package-debian.sh
