FROM debian:buster

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y -o Acquire::Retries=10 \
        ca-certificates \
        curl \
        devscripts \
        dirmngr \
        gnupg \
        tee \
        vim

RUN curl --retry 10 -s https://dl.jami.net/public-key.gpg | \
    tee /usr/share/keyrings/jami-archive-keyring.gpg > /dev/null
RUN sh -c "echo 'deb [signed-by=/usr/share/keyrings/jami-archive-keyring.gpg] https://dl.jami.net/internal/debian_10_qt/ jami main' > /etc/apt/sources.list.d/qt-jami.list"

# add/enable src repos (needed for next step)
RUN sed -n '/^deb\s/s//deb-src /p' /etc/apt/sources.list > /etc/apt/sources.list.d/deb-src.list

RUN apt-get clean && apt-get update
RUN if [ -z "${OVERRIDE_PACKAGING_DIR}" ]; then \
        cd "packaging/rules" && mk-build-deps \
            --remove --install \
            --tool "apt-get -y --no-install-recommends -o Acquire::Retries=10" \
            "debian/control"; \
    else \
        cd "${OVERRIDE_PACKAGING_DIR}" && mk-build-deps \
            --remove --install \
            --tool "apt-get -y --no-install-recommends -o Acquire::Retries=10" \
            "control"; \
    fi

ADD scripts/build-package-debian.sh /opt/build-package-debian.sh

CMD /opt/build-package-debian.sh
