FROM ubuntu:19.04
# Non root user with sudo
RUN apt-get update && apt-get install --no-install-recommends -y sudo
RUN useradd -ms /bin/bash -G sudo user
RUN sed -i 's/^%sudo.*/%sudo ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
# Required to add jami repos to debian

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get install --no-install-recommends -y \
        gnupg \
        dirmngr \
        ca-certificates \
        apt-transport-https
RUN apt-get clean
RUN apt-get update && \
    apt-get install -y vim devscripts equivs \
        binutils \
        xz-utils \
        wget
RUN apt install --no-install-recommends -y \
        libqt5sql5-sqlite \
	gnupg \
	libargon2-1  \
	libasound2  \
	libavcodec58  \
	libavdevice58  \
	libavfilter7  \
	libavformat58  \
	libavutil56  \
	libayatana-appindicator3-1  \
	libc6  \
	libcairo2  \
	libcanberra-gtk3-0  \
	libcanberra0  \
	libclutter-1.0-0  \
	libclutter-gtk-1.0-0  \
	libdbus-1-3  \
	libgcc1  \
	libgdk-pixbuf2.0-0  \
	libglib2.0-0  \
	libgtk-3-0  \
	libhogweed4  \
	libixml10  \
	libjsoncpp1  \
	libnatpmp1  \
	libnettle6  \
	libnm0  \
	libnotify4  \
	libpango-1.0-0  \
	libpulse0  \
	libqrencode4  \
	libqt5core5a  \
	libqt5dbus5  \
	libqt5gui5  \
	libqt5sql5  \
	libssl1.1  \
	libstdc++6  \
	libswresample3  \
	libswscale5  \
	libudev1  \
	libupnp13  \
	libuuid1  \
	libwebkit2gtk-4.0-37  \
	libx11-6 \
	libyaml-cpp0.6  \
	zlib1g  \
	dconf-gsettings-backend \
        gsettings-backend 
USER user
WORKDIR /home/user
